openapi: 3.0.3
info:
  title: Анализатор темы текста
  description: |-
    Сервис, анализирующий принадлежность текста указанной теме
  version: 0.0.1
tags:
  - name: Анализ
    description: Получение текстов и выдача результатов
paths:
  /process:
    post:
      tags:
        - Анализ
      summary: Проанализировать текст
      description: Проанализировать текст по указанной теме
      operationId: processText
      requestBody:
        description: Пара тема-текст
        content:
          application/json:
            schema:
             $ref: '#/components/schemas/InputText'
        required: true
      responses:
        '200':
          description: Текст отправлен на обработку
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UuidResponse'
  /processed:
    get:
      tags:
        - Анализ
      summary: Получить результаты анализа
      description: Получить веса принадлежности теме
      operationId: processedText
      parameters:
        - name: id
          in: query
          description: UUID, полученный из /process
          required: true
          explode: true
          schema:
            type: string
            example: 91b6d14b-c099-431e-a447-c5c8ec2cbd29
      responses:
        '200':
          description: Обработанные фрагменты текста
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReferenceSamples'
components:
  schemas:
    ReferenceSamples:
      type: array
      items:
        type: object
        properties:
          theme:
            type: string
            example: Тема
          id:
            type: string
            example: 91b6d14b-c099-431e-a447-c5c8ec2cbd29
          part:
            type: integer
            example: 0
          weight:
            type: number
            example: 1.0
    UuidResponse:
      type: object
      properties:
        uuid:
          type: string
          example: 91b6d14b-c099-431e-a447-c5c8ec2cbd29
    InputText:
      type: object
      properties:
        theme:
          type: string
          example: Тема
        text:
          type: string
          example: Данный текст принадлежит какой-нибудь теме
