# Generated by Django 5.0.1 on 2024-01-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReferenceSample",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("part", models.IntegerField()),
                ("order1", models.TextField(blank=True, null=True)),
                ("order2", models.TextField(blank=True, null=True)),
                ("order3", models.TextField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("theme", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "reference_samples",
                "unique_together": {("id", "part")},
            },
        ),
    ]
